### PR TITLE
Bug: When closing a note, the text is pasted into the search

### LINKED ISSUE #149: When I close note, I paste text to search
Steps
- Copy any text to a clipboard
- Open note
- Focus on search input
- Click middle mouse button to close note tab

Current behaviour:
- Note is closed
- Text from clipboard inserted to a search input

Text must not be inserted. User may have sensitive data in clipboard

Problem is reproduced on Linux Ubuntu KDE.

### PR DESCRIPTION
**Pull request by katsyuta**
Closes #149 

The problem is specific to X11 systems, such as KDE: clicking the middle mouse button pastes the selected text into the currently focused element, even when clicking on a different element.

**Solution:**
Prevent text from being inserted into the focused field when the middle-click occurs on another element.

We listen to the `mouseup` event because the OS performs the paste on button release. Using `mousedown` doesn’t work, and `click` is too late, as the paste has already occurred.

As a result, middle-click paste only works when the clicked element is the same as the currently focused element.

### CODE REVIEW

**Comment by katsyuta** [comment]
@vitonsky, can you review this pull request ?

File: src/features/MainScreen/index.tsx [hunk 1]
```diff
@@ -30,6 +30,29 @@ export const MainScreen: FC = () => {
...
 
+	useEffect(() => {
+		const preventTextInsert = (e: MouseEvent) => {
+			if (e.button !== 1) return;
+
+			const isEditable = e.composedPath().some((element) => {
+				return (
+					element instanceof HTMLInputElement ||
+					element instanceof HTMLTextAreaElement ||
+					(element instanceof HTMLElement && element.isContentEditable)
```
Comment (vitonsky) [inline src/features/MainScreen/index.tsx]: This code potentially may run frequently, so 3 times to check for proto per run sounds expensive.
We could replace it to check a `tagName` for `INPUT` and `TEXTAREA`.

Check for element may be replaced via check `nodeType` for `Node.ELEMENT_NODE` https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType

File: src/features/MainScreen/index.tsx [hunk 2]
```diff
@@ -30,6 +30,29 @@ export const MainScreen: FC = () => {
 		});
 	}, [tagsRegistry, updateNotes]);
 
+	useEffect(() => {
+		const preventTextInsert = (e: MouseEvent) => {
+			if (e.button !== 1) return;
```
Comment (vitonsky) [inline src/features/MainScreen/index.tsx]: Explain in code this magical number

File: src/features/MainScreen/index.tsx [hunk 3]
```diff
@@ -30,6 +30,29 @@ export const MainScreen: FC = () => {
...
+				return (
+					element instanceof HTMLInputElement ||
+					element instanceof HTMLTextAreaElement ||
+					(element instanceof HTMLElement && element.isContentEditable)
+				);
+			});
+
+			if (!isEditable) {
+				// Prevent a KDE/X11 issue where pressing the middle mouse button pastes text
+				// from the clipboard into the focused element, even when clicking another element
```
Comment (vitonsky) [inline src/features/MainScreen/index.tsx]: Move description at top of this function. We should explain such things at start of the code
