### PR TITLE
fix: new workspace is not saved after reload app

### LINKED ISSUE #225: Bug: If the app is reloaded immediately after creating a workspace, the workspace is not saved
If the application is reloaded immediately after creating a workspace, the next load will fail to load the last active workspace and the application look like crashes.

The ID of the newly created workspace is written to the vault state file, and when loading the vault we read this ID from the file. However, the database does not return this workspace because the application was closed before saved to the database.

When loading the vault state, we can add a check to verify whether the last active workspace actually exists in the database. This would prevent the application from crashing in such cases.

However, to ensure that the user does not lose the created workspace, we must guarantee that it is properly saved to the database before its ID is written to the vault state.

### PR DESCRIPTION
**Pull request by katsyuta**
Closed #225 

**Problem**: 
If the app is reloaded immediately after creating a workspace, it may not yet be saved to the file system, causing the app to try loading a non-existent workspace and resulting in a white screen. 
This happens because the database is not synchronized with the file system immediately after creation workspace. We sync changes at intervals, but the user may reload the app before the automatic synchronization occurs.

**Fix**: 
- Sync immediately after creating a workspace
- Check if the workspace from the vault state really exists in the database
- Update the active workspace in Redux only if it exists in Redux

These changes ensure that the workspace is saved after creation and prevent the app from trying to load a non-existent workspace

Changes:
- Refactor PropertiesForm: move it to the shared components directory and add the isPending prop
- Update ESLint: enable rules and disallow non-strict equality

https://github.com/user-attachments/assets/d6b17ef5-92db-4fa2-ad1b-301fc7798cc3

## Summary by CodeRabbit

* **Bug Fixes**
  * Enhanced workspace validation to ensure the active workspace exists before use
  * Improved data persistence with automatic synchronization during workspace creation
  * Added guards to prevent duplicate workspace creation submissions
  * Workspace names are now trimmed of whitespace during validation

* **Chores**
  * Refactored form components for improved code reusability
  * Updated code quality standards to enforce stricter equality checks

### CODE REVIEW

File: src/features/NoteEditor/RichEditor/plugins/ContextMenu/components/ObjectPropertiesEditor.tsx
Comment (vitonsky) [inline src/features/NoteEditor/RichEditor/plugins/ContextMenu/components/ObjectPropertiesEditor.tsx]: Why this component is changed? It looks irrelevant

File: src/features/MainScreen/WorkspacesPanel/WorkspaceCreatePopup.tsx [hunk 1]
```diff
@@ -65,12 +66,19 @@ export const WorkspaceCreatePopup = () => {
...
 
 								workspacesManager
 									.create({ name })
 									.then(async (workspaceId) => {
+										// Synchronize immediately after creation to prevent workspace loss
+										// if the user closes the app before the automatic sync
+										await db.sync();
+
+										setIsCreating(false);
+										onClose();
```
Comment (vitonsky) [inline src/features/MainScreen/WorkspacesPanel/WorkspaceCreatePopup.tsx]: Too early close

File: src/features/MainScreen/WorkspacesPanel/WorkspaceCreatePopup.tsx [hunk 2]
```diff
@@ -65,12 +66,19 @@ export const WorkspaceCreatePopup = () => {
...
+								setIsCreating(true);
 
 								workspacesManager
 									.create({ name })
 									.then(async (workspaceId) => {
+										// Synchronize immediately after creation to prevent workspace loss
+										// if the user closes the app before the automatic sync
+										await db.sync();
+
+										setIsCreating(false);
```
Comment (vitonsky) [inline src/features/MainScreen/WorkspacesPanel/WorkspaceCreatePopup.tsx]: What if this promise will be rejected?

File: src/features/NoteEditor/RichEditor/plugins/Markdown/MarkdownShortcutPlugin.tsx [hunk 3]
```diff
@@ -64,7 +64,7 @@ export const $transformTextToCheckbox = (textNode: TextNode) => {
 		// if (parent instanceof ListItemNode) return;
 		if (!(parent instanceof ParagraphNode)) return;
 
-		const isChecked = checkboxMatch[2] != ' ';
+		const isChecked = checkboxMatch[2] !== ' ';
```
Comment (katsyuta) [inline src/features/NoteEditor/RichEditor/plugins/Markdown/MarkdownShortcutPlugin.tsx]: In both case we compare two string and using strict equality check is ok

File: src/state/redux/profiles/profiles.ts [hunk 4]
```diff
@@ -212,14 +212,19 @@ export const profilesSlice = createSlice({
 			const profile = state.profiles[profileId];
 			if (!profile) return;
 
+			if (!workspaceId) {
+				profile.activeWorkspace = workspaceId;
+				return;
+			}
```
[the remark this answers is not in the document]
Comment (katsyuta) [reply src/state/redux/profiles/profiles.ts]: If we pass null into the reducer, it means we want to reset the active workspace and do nothing else

File: src/features/MainScreen/WorkspacesPanel/WorkspaceCreatePopup.tsx [hunk 5]
```diff
@@ -41,55 +42,109 @@ export const WorkspaceCreatePopup = () => {
 
 	const { update: updateWorkspaces } = useWorkspacesList();
 
+	const inputNameRef = useRef<HTMLInputElement | null>(null);
+
+	const [workspaceName, setWorkspaceName] = useState<string>('');
+	const [isPending, setIsPending] = useState(false);
+	const [errorMessage, setErrorMessage] = useState<string | null>(null);
+
+	const onCreate = useCallback(async () => {
```
Comment (vitonsky) [inline src/features/MainScreen/WorkspacesPanel/WorkspaceCreatePopup.tsx]: Why this changes is needed?

**Review by vitonsky — APPROVED** [review]
