### PR TITLE
fix: Note is sometimes updates while opening

### LINKED ISSUE #258: Note is sometimes updates while opening
When I open a note just by click it, the note updates and goes to the notes list top.

That is unexpected behaviour, since i did not changed a note content.

This behaviour makes difficult a notes exploring.

I use a rich editor.

I don't know exact steps, but when that happens, i noticed the history changes, and new entry in history have different chars counter.

I think the problem is RichEditor changes the text when open a note, and writes a changes. We should find a minimal steps to reproduce first.

### PR DESCRIPTION
**Pull request by katsyuta**
Closes #258 

When user open note, the RichEditor component receive the note text as property.
The serializer plugin react on that as on update, and serialize the input.
In case the input and output are different the change is triggered.
The output may be different because of different implementation of markdown parser/serializer.
It happens mostly when markdown contains advanced constructions like title for link in your example.

In scope of this PR we introduce the code to prevent serialization of any input except user input via keyboard into editor component.

Technically we mark any other inputs via special tag and skip serialization for changes with that tag.

---

The root problem: When we receive the external value - we update editor, this trigger the OnChangePlugin witch update external value and then note updated. But value is changed not user initiated. I suggests ignore this update and not update note in this case

The current flow in `MarkdownSerializePlugin`:
**External value update:** 
* Effect triggers
* Check if value equals local ref - if equal, early return (ignore own update)
* Update editor

**OnChangePlugin triggers:**
* Serialize markdown to string and save result to local ref
* Update external state

User made no real changes, but the note was updated.

**Fix:** 
Tag editor updates made by us in useEffect and ignore them in `OnChangePlugin`.

Updated flow in `MarkdownSerializePlugin`:

**External value changed:**
* Effect triggers
* Check if value equals local ref — if equal, early return
* Update editor with special tag

**OnChangePlugin triggers:**
* Check if update has special tag — if so, skip state update *(not a user-initiated change)*
* Serialize editor nodes to markdown string and save result to local ref
* Update external state

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed markdown editor synchronization so programmatic/internal editor updates no longer trigger the debounced sync to external state. Only direct user edits now cause markdown→prop syncing, reducing redundant updates, preventing spurious change events, and improving overall change handling and performance.

### CODE REVIEW

**Comment by katsyuta** [comment]
@coderabbitai full review

File: src/features/NoteEditor/RichEditor/plugins/Markdown/MarkdownSerializePlugin.tsx
Comment (vitonsky) [inline src/features/NoteEditor/RichEditor/plugins/Markdown/MarkdownSerializePlugin.tsx:1]: How it does work with the input loops when
- user input text
- it triggers the onChange and serializes the data
- react state updates
- input goes goes back to that component as updated `value`

What happens in that situation?

Comment (katsyuta) [reply src/features/NoteEditor/RichEditor/plugins/Markdown/MarkdownSerializePlugin.tsx:1]: This component ignores value updates that it made itself. When serializing editor content, the result is saved to a local ref. When a re-render occurs it compares the external value with that ref - if they are equal, the editor update is skipped.

The whole flow for MarkdownSerializePlugin is as follows:

**External value changed:**
- Effect triggers
- Check if value equals local ref - if equal, early return *(ignore own update)*
- Update editor with special tag

**OnChangePlugin triggers:**
- Check if update has special tag - if so, ignore *(not a user-initiated change)*
- Serialize editor nodes to markdown string and save result to local ref *(prevents loop on next external update)*
- Update external state

We update the editor manually only if the external value is not equal to the local ref: when the editor first renders or when the user applies history

File: src/features/NoteEditor/RichEditor/plugins/Markdown/MarkdownSerializePlugin.tsx [hunk 1]
```diff
@@ -61,7 +64,10 @@ export const MarkdownSerializePlugin = ({
 	return (
 		<OnChangePlugin
 			ignoreSelectionChange
-			onChange={(_, editor) => {
+			onChange={(_, editor, tags) => {
+				// Ignore updates initiated by useEffect to prevent loop between editor and external state
```
Comment (vitonsky) [inline src/features/NoteEditor/RichEditor/plugins/Markdown/MarkdownSerializePlugin.tsx]: That is very confused comment.

How this change prevents the loop?
How to reproduce the loop if we will not apply this change?
Why you mention `useEffect` here?

**Review by vitonsky — APPROVED** [review]
