### PR TITLE
fix: after calling confirm focus is lost

### LINKED ISSUE #139: Bug: After calling confirm, the application stops responding to user interactions
**Problem:** After calling confirm function the element loses focus.

**Expected Behavior:** For actions that require confirmation (e.g., deleting a tag), after pressing 'ок' or 'cancel', the modal should close and all app elements should work normally (e.g., the search input remains usable).

**Actual Behavior:** After the confirm dialog closes, UI elements do not respond to clicks.

**Steps to reproduce:**
- Select a tag
- Open the context menu
- Choose Delete
- Confirm the action
- Click on the search input to enter text

This issue appeared after updating Electron. I found multiple reports about it in electron’s issues. As I understand, this has been a long-standing problem that is still not reliably fixed: https://github.com/electron/electron/issues/31917

### Possible Solutions:

1) Use showMessageBox in the renderer process (recommended in the same issue):
```
const result = await dialog.showMessageBox({
    type: 'question',
    buttons: ['Yes', 'No'],
    defaultId: 0,
    cancelId: 1,
    title: title,
    message: message,
});
console.log(result.response);
return result.response === 0;
```
I implemented this solution and it works well.

2) Use a React-based confirm dialog.
The most of the current code uses electron confirm. So, the first solution better.

I can resolve this issue. The this [documentation](https://github.com/vitonsky/deepink/blob/0a17da483014a452cd3364d84eab502023d73b96/src/electron/utils/ipc/README.md) here helped me understand how to handle communication between the main and renderer processes.

### PR DESCRIPTION
**Pull request by katsyuta**
Closes #139 

**Problem:**
Calling confirm causes the window to lose focus. Solutions [like this](https://github.com/electron/electron/issues/31917#issuecomment-2629239305) don’t work because they require calling blur(), which collapses the window, so they aren’t suitable.

Calling blur() is needed to reset the window’s internal focus state, which still stays focused (window.isFocused == true) , even though in fact the window has no focus. Only after that can focus() correctly restore the OS-level focus.

**Solution**
The only working solution I found is to use `dialog.showMessageBoxSync`. 
To preserve synchronous behavior use showMessageBoxSync along with ipcRenderer.sendSync.
Visually dialog.showMessageBoxSync does not differ from confirm

### CODE REVIEW

File: src/electron/requests/confirm/renderer.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+export interface ElectronAPI {
+	confirm: (message?: string) => boolean;
+}
+
+declare global {
+	interface Window {
+		electron: ElectronAPI;
+	}
+}
```
Comment (vitonsky) [inline src/electron/requests/confirm/renderer.ts]: Remove it, since it set types on whole app as i understand

File: src/electron/requests/confirm/main.ts
Comment (vitonsky) [inline src/electron/requests/confirm/main.ts]: We should not to introduce a fix for each broken feature.
Instead of `confirm` we should introduce an electron patch, place all fixes there and call it only once, but in every window.

You missed an `about` window

**Review by vitonsky — APPROVED** [review]
