### PR TITLE
fix: Modal window for creating tags does not handle Enter

### LINKED ISSUE #247: Modal window for creating tags does not handle Enter
All modals in app with inputs handle Enter, which is very convenient. Maybe we should introduce this behavior for the Tag Editor modal as well

### PR DESCRIPTION
**Pull request by katsyuta**
Closes #247 

Add `form` wrapper to handle Enter key

## Summary by CodeRabbit

* **Refactor**
  * Tag editor now uses a standard form submit flow for saving.
  * Prevents duplicate submissions by disabling actions during async save.
  * Primary action is a submit button; tag names are trimmed before saving.
  * Validation and save errors are surfaced reliably; editor only closes after a successful save.

### CODE REVIEW

File: src/components/TagEditor/index.tsx [hunk 1]
```diff
@@ -135,39 +164,14 @@ export const TagEditor: FC<ITagEditorProps> = ({
...
-									'Unable to save the tag. Please try again.',
-								);
-							}
-						}}
-					>
+					<Button type="submit" variant="accent" isDisabled={isPending}>
 						{isEditingMode ? 'Save' : 'Add'}
 					</Button>
-					<Button onClick={onCancel}>Cancel</Button>
+					<Button onClick={onCancel} isDisabled={isPending}>
```
Comment (vitonsky) [inline src/components/TagEditor/index.tsx]: Why we block "Cancel" button while pending state?
What if user will want to skip the operation?
Is there may be any problems then?

Comment (katsyuta) [reply src/components/TagEditor/index.tsx]: I agree it is better not to block cancel. I don’t think there is any significant problem here without blocking it

**Review by vitonsky — APPROVED** [review]
