### PR TITLE
fix: white screen after deleting a workspace

### LINKED ISSUE #231: Bug: White screen after deleting a workspace
Steps to reproduce:
- Create a vault
- Create a new workspace
- Reload the app
- Delete the current workspace
- See a white screen

I'm not completely sure, but it seems this happens because the `touched` property for the workspace that becomes active instead of the deleted one is not being updated somewhere. 

Also after deleting a workspace the directory for the deleted workspace still exists

### PR DESCRIPTION
**Pull request by katsyuta**
Closed #231 

**1) White Screen after delete:**
The bug happens because after deleting workspace the active workspace, its touch property is set to false, so it is not rendered. This occurs due to the following flow when deleting a workspace:
- Call `setActiveWorkspace`, which updates the touch property for the workspace.
- Call the `useWorkspacesList` hook to update the workspace list; the hook uses a stale closure where the active workspace’s touch is still false. When updating redux in this hook, we overwrite the `touch` property of the active workspace and we have bug

To fix this error, i moved the update workspaces logic from `useWorkspacesList` to Redux, so the reducer has the actual state where touch for the active workspace is true. 

**2) Workspace dir not deleted:**
This happens because we had no logic to delete this directory. I added.

## Summary by CodeRabbit

* **New Features**
  * Added workspace file controller support so workspace-scoped files are managed and exposed where relevant.

* **Bug Fixes**
  * Workspace deletion now removes associated configuration files to prevent orphaned data.

* **Refactor**
  * Simplified workspace list synchronization and updated workspace store handling to perform targeted create/update/delete operations for more reliable state management.

### CODE REVIEW

**Comment by katsyuta** [comment]
@vitonsky, Pull request is ready for review!

File: src/state/redux/profiles/profiles.ts [hunk 1]
```diff
@@ -189,18 +189,37 @@ export const profilesSlice = createSlice({
 			state.activeProfile = payload;
 		},
 
-		setWorkspaces: (
+		syncWorkspacesList: (
```
Comment (vitonsky) [inline src/state/redux/profiles/profiles.ts]: Why it's called "sync"?

**Review by vitonsky — CHANGES_REQUESTED** [review]
Generally it is unclear why the problem happens.

According to your description
> This happens because we dispatch the setActiveWorkspace to update the touch property, and after that we call the callback to update the workspace list in Redux.

I can't see the changes related to this logic

File: src/features/App/Settings/sections/WorkspaceSettings.tsx [hunk 2]
```diff
@@ -78,6 +80,7 @@ export const WorkspaceSettings = () => {
 	const files = useFilesRegistry();
 	const filesController = useFilesController();
 	const attachments = useAttachmentsController();
+	const workspaceFiles = useVaultStorage(getWorkspaceRoot());
```
Comment (vitonsky) [inline src/features/App/Settings/sections/WorkspaceSettings.tsx]: Scope the current workspace

```suggestion
	const workspaceFiles = useVaultStorage(getWorkspacePath(currentWorkspace.workspaceId));
```

File: src/features/App/Settings/sections/WorkspaceSettings.tsx [hunk 3]
```diff
@@ -115,6 +118,9 @@ export const WorkspaceSettings = () => {
 			attachments,
 		}).fixAll();
 
+		// Delete workspace directory
+		await workspaceFiles.delete([currentWorkspace.workspaceId]);
```
Comment (vitonsky) [inline src/features/App/Settings/sections/WorkspaceSettings.tsx]: Delete whole directory with a current workspace

```suggestion
		await workspaceFiles.delete(['/']);
```

File: src/state/redux/profiles/profiles.ts
Comment (vitonsky) [inline src/state/redux/profiles/profiles.ts]: The `set` prefix means we set state as is.
That looks more like update of workspaces list. So it may be named as `updateWorkspacesList`

**Review by vitonsky — APPROVED** [review]
